spring:
  datasource:
    url: jdbc:mysql://localhost:3306/heartscopydb
    username: root
    password: Nudw236565
    driver-class-name: com.mysql.cj.jdbc.Driver
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true